targets:
  openapi_parser_builder:
    builders:
      openapi_parser_builder:schemaBuilder:
        enabled: true

builders:
  schemaBuilder:
    import: package:openapi_parser_builder/openapi_parser_builder.dart
    builder_factories: [ schemaBuilder ]
    build_extensions:
      input/openapi_spec.md: [ output/schema_classes.dart ]
    build_to: source
    auto_apply: root_package
