targets:
  openapi_client_builder:
    builders:
      openapi_client_builder:schemaBuilder:
        enabled: true
      openapi_client_builder:clientBuilder:
        enabled: true

builders:
  schemaBuilder:
    import: package:openapi_client_builder/openapi_schema_builder.dart
    builder_factories: [ schemaBuilder ]
    build_extensions:
      input/openapi_spec.md: [ output/schema_classes.dart ]
    build_to: source
    auto_apply: root_package
    runs_before: [ openapi_client_builder:clientBuilder ]
  clientBuilder:
    import: 'package:openapi_client_builder/openapi_client_builder.dart'
    builder_factories: [ clientBuilder ]
    build_extensions:
      input/app-store-connect-openapi.json: [ output/client.dart ]
    build_to: source
    auto_apply: root_package
