targets:
  openapi_client_builder_builder:openapi_client_builder_builder:
    builders:
      openapi_client_builder_builder|clientBuilderBuilder:
        enabled: True

builders:
  clientBuilder:
    import: 'package:openapi_client_builder_builder/openapi_client_builder_builder.dart'
    builder_factories: ['clientBuilderBuilder']
    build_extensions:
      input/openapi_spec.md:
        - output/schema_classes.dart
    build_to: source
    auto_apply: root_package
