name: openapi_schema_builder
description: Build openapi clients from the OpenApi specification.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  build: any
  path: any
  markdown: any
  html: any

dev_dependencies:
  build_config: any
  build_runner: any
  pedantic: any
  test: any